### ISSUE TITLE
Keywords are highlighted but variables aren't

### ISSUE THREAD

**Issue by C0rn3j** [rodolphebarbanneau/python-docstring-highlighter#6]
![image](https://github.com/user-attachments/assets/ddfa7f29-6d39-456c-b308-06f36c733033)

```python
def shell_exec(*, args:list[str]|str, timeout: int = 150) -> tuple[CommandOutput, list[str]|None]:
	"""Execute a shell command with subprocess.

	Args:
		args: Command and arguments to execute.
		timeout: Maximum time in seconds to wait for the command to complete.

	Returns:
		CommandOutput: An object containing the returncode, stdout, and stderr.

	Raises:
		ShellExecError: If an error occurs during command execution.

	"""
```

```yaml
# VSC extensions
Pyright: v1.1.374 
Python: v2024.12.1

# VSC
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-08-01T22:07:15.925Z
Electron: 30.3.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.9.7-arch1-1
```

Theme used is Night Owl, randomly tried another one and it had the same issue.
